name: multisite-fx
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies for Colmena
  - python==3.8.*
  - redis==5.0.3
  - redis-py==3.4.1
  - jupyterlab
  - pytest
  - flake8
  - pip

  # Dependencies from the molecular design app
  - matplotlib==3.3.3
  - openbabel==3.0.0
  - geometric==0.9.*
  - qcengine==0.23.0
  - pyyaml < 6
  - rdkit==2019.09.3
  - tensorflow-mkl==2.4.1
  - py-cpuinfo<6
  - msgpack-python==1.*
  - xtb-python
  - psutil
  - tqdm

  # Pip packages for all of them
  - pip:
      - -e .
      - ase==3.22.1
      - funcx==0.3.9
      - funcx_endpoint==0.3.3
      - python-git-info
      - flatten-dict
      - colmena==0.3.*
